'use strict';

const child = require('child_process');
const roles = require('./roles');
const path = require('path');
const fs = require('fs');
const os = require('os');

/**
 * xcompile evaluates and compiles the roles to Go.
 */
function xcompile(target, callback) {
    const fmt = child.spawn('gofmt');
    fmt.stderr.pipe(process.stdout);
    fmt.stdout.pipe(fs.createWriteStream(target));

    fmt.stdin.write(`
        // AUTOGENERATED FILE, DO NOT EDIT

        package bcommon

        var (
    `);

    Object.keys(roles.list).forEach(key => {
        const role = roles.list[key];
        const perms = roles.getPermissions([key])
            .map(item => `"${item}",\n`)
            .join('');

        fmt.stdin.write(`
            ${role.name} = &Role{
                Name: "${role.name}",
                Exclusivity: ${role.exclusivity|0},
                Level: ${role.level},
                Permissions: []string{\n${perms}},
            }`
        );
    });

    fmt.stdin.write(`
        )

        var RoleMap = map[string]*Role{
    `);

    Object.keys(roles.list).forEach(name => {
        fmt.stdin.write(`"${name}": ${name},\n`);
    });

    fmt.stdin.write(`}`);
    fmt.stdin.end();

    fmt.on('exit', (code) => callback(code));
}

module.exports = xcompile;


if (require.main === module) {
    xcompile(
        path.join(__dirname, 'go/bcommon/roles.go'),
        (code) => process.exit(code)
    );
}
